export const W_core_ancestries = ["Dwarf", "Elf", "Halfling", "Human"];

export const W_extended_ancestries = [
  "Half-Dwarf",
  "Half-Elf",
  "Gnome",
  "Half-Giant",
  "Half-Orc",
  "Pixie",
  "Half-Devil",
  "Half-Angel",
  "Half-Elemental",
];

export const Basic_Animal_hybrid_ancestries = [
  "Cat",
  "Dragon",
  "Lizard",
  "Bird",
  "Fox",
  "Fish",
  "Frog",
  "Dog",
  "Wolf",
  "Snake",
  "Scorpion",
  "Spider",
  "Bear",
  "Horse",
  "Cow",
  "Goat",
  "Deer",
  "Pig",
  "Rat",
  "Bat",
];

export type AncestrySetSelection = "Core" | "Extended" | "Beastman";

// export const Extended_Felidae_Hybrid_Ancestries = [
//   "Lion",
//   "Tiger",
//   "Panther",
//   "Puma",
//   "Jaguar",
//   "Leopard",
//   "Snow Leopard",
//   "Caracal",
//   "Lynx",
//   "Ocelot",
// ];

// export const Extended_Caninae_Hybrid_Ancestries = [
//   "Wolf",
//   "Zorro de Chilote",
//   "Zorro gris",
//   "Hoary Zorro",
//   "Maikong",
//   "Raccoon Dog",
//   "Gray Fox",
//   "Coyote",
//   "Gray Wolf",
//   "Red Jackal",
//   "Maned Wolf",
//   "Corsac Fox",
//   "Tibetan Fox",
//   "Red Fox",
//   "Fennec Fox",
// ];

// export const Extended_Avus_Hybrid_Ancestries = [
//   "Ostrich",
//   "Kiwi",
//   "Emu",
//   "Cassowary",
//   "Duck",
//   "Goose",
//   "Flamingo",
//   "Pigeon",
//   "Dove",
//   "Falcon",
//   "Parrots",
//   "Woodpeckers",
//   "Kingfisher",
//   "Hornbill",
//   "Owl",
//   "Hawk",
//   "Eagle",
//   "Pelican",
//   "Vulture",
//   "Heron",
//   "Stork",
//   "Loon",
//   "Gull",
//   "Swift",
// ];
